### ISSUE TITLE
Support for comparing functions

### ISSUE THREAD

**Issue by marcelmokos** [epoberezkin/fast-deep-equal#24]
We are using `react-fast-compare` and I need to compare functions in react when they are used as props. I have created PR to the `react-fast-compare` repository. They referenced me to try to get the change implemented here.

Are you open for PR implementing function comparison?

Original commit.
https://github.com/marcelmokos/react-fast-compare/commit/887600a03fef8e93779f06c78367b8ee8dd5ebb4

**Comment by epoberezkin** [comment]
Functions are compared by reference, as they should be - the test is here: 
https://github.com/epoberezkin/fast-deep-equal/blob/master/spec/tests.js#L331
