### ISSUE TITLE
Comparing Proxies of RegExp throws

### ISSUE THREAD

**Issue by zandaqo** [epoberezkin/fast-deep-equal#25]
Apparently, RegExp#toString doesn't like being called on a proxy, and throws the following error:
```
TypeError: RegExp.prototype.source getter called on non-RegExp object
```
and that's what happen on this line: https://github.com/epoberezkin/fast-deep-equal/blob/8a9c22e36a18a0b6a006d180572016c91e9f23e1/index.js#L35 of the library when you try to compare proxies of regexps.

This is such an edge case that I'm not sure it's worth solving in this library, but I decided to share just in case anyone else encounters it.

**Comment by sirlancelot** [comment]
I wonder if instead of explicitly calling `.toString()`, you were to use `String(a) === String(b)`?

**Comment by zandaqo** [comment]
@sirlancelot Nope, it still calls `RegExp#toString` under the hood with the same result.

**Comment by epoberezkin** [comment]
Tracked in #32

**Comment by epoberezkin** [comment]
I don't think it can be solved - RegExp does not support proxying it seems
