### ISSUE TITLE
Map object returns true regardless of key entries

### ISSUE THREAD

**Issue by reallistic** [epoberezkin/fast-deep-equal#26]
Copied from node console:

```
> const equal = require('fast-deep-equal');
undefined
> const mapA = new Map();
undefined
> const mapB = new Map();
undefined
> equal(mapA, mapB)
true
> mapA.set('a', 1);
Map { 'a' => 1 }
> equal(mapA, mapB)
true
```

My guess is because they both have the same key properties

**Comment by toburger** [comment]
The same is true for Sets:

```js
> equal(new Set([1]), new Set([2]))
true
```

**Comment by epoberezkin** [comment]
It essentially doesn't support all new JavaScript primitives...

**Comment by tracksaw** [comment]
Please document this. It just caught me out...

**Comment by taw** [comment]
Oh I just came to report this problem. Looks like it's already reported.

**Comment by epoberezkin** [comment]
Tracked in #32

**Comment by epoberezkin** [comment]
released in [beta](https://github.com/epoberezkin/fast-deep-equal/releases/tag/v3.0.0-beta.0)
