### ISSUE TITLE
Typescript is listed as a devdependency but is a production dependency

### ISSUE THREAD

**Issue by seanrich** [epoberezkin/fast-deep-equal#27]
The package.json for the project only lists devDependencies, this prevents this module from being installed using --production.

**Comment by epoberezkin** [comment]
Why typescript is a production dependency? I don't think it is.

**Comment by Rycochet** [comment]
Typescript is the compiler, and you're only using it for testing (btw, add `--noEmit` to let it know that it never outputs anything).

So yes, bad project configuration - `typescript` should *never* be a direct production dependancy. For NodeJS you can import `ts-node` to allow direct use, and no browser supports it directly.
