### ISSUE TITLE
JSON.stringify test

### ISSUE THREAD

**Issue by ar53n** [epoberezkin/fast-deep-equal#30]
Lets add JSON.stringify test for comparasion?

**Comment by epoberezkin** [comment]
I don’t think it’s a viable option - the result would depend on the order of keys...

**Comment by kirillgroshkov** [comment]
Why not? I was puzzled by the same question - should I use this lib or JSON.stringify for comparison? What's faster? (for general purpose json objects)

**Comment by epoberezkin** [comment]
JSON.stringify cannot be used to compare objects - different order of the same keys will produce different strings

**Comment by epoberezkin** [comment]
Try with {a:1, b:2} and {b:2, a:1} - objects are equal but JSON.stringify will produce different strings

**Comment by kirillgroshkov** [comment]
> JSON.stringify cannot be used to compare objects - different order of the same keys will produce different strings

You're right. What I actually meant is to first run `jsonSort` function which is supposed to deterministically sort json object (there are different implementations in the wild), and then compare `JSON.stringify` of them.

**Comment by AlexanderMykulych** [comment]
Hi! Had the same question. I've added `JSON.stringify` to benchmarks and here is my result:
fast-deep-equal x 274,197 ops/sec ±1.22% (89 runs sampled)
fast-deep-equal/es6 x 230,640 ops/sec ±1.01% (89 runs sampled)
fast-equals x 266,722 ops/sec ±1.04% (88 runs sampled)
nano-equal x 193,028 ops/sec ±0.84% (96 runs sampled)
shallow-equal-fuzzy x 149,221 ops/sec ±1.16% (93 runs sampled)
underscore.isEqual x 90,271 ops/sec ±1.88% (90 runs sampled)
lodash.isEqual x 41,025 ops/sec ±0.86% (92 runs sampled)
deep-equal x 240 ops/sec ±0.62% (60 runs sampled)
deep-eql x 42,406 ops/sec ±1.07% (96 runs sampled)
ramda.equals x 12,885 ops/sec ±0.87% (97 runs sampled)
util.isDeepStrictEqual x 55,503 ops/sec ±0.96% (94 runs sampled)
assert.deepStrictEqual x 529 ops/sec ±0.36% (92 runs sampled)
stringify x 37,691 ops/sec ±0.65% (98 runs sampled)
