### ISSUE TITLE
Does not work with two identical function declarations

### ISSUE THREAD

**Issue by agrosner** [epoberezkin/fast-deep-equal#31]
I got a class called `LoadingModel` and it is represented as:
```
export class LoadingModel<T> {

  static empty = <T>() => new LoadingModel<T>(false, false, false, undefined)

  static success<T>(success: T): LoadingModel<T> {
    return new LoadingModel(false, false, true, success)
  }

  static error<T>(error?: Error, optionalSuccess?: T): LoadingModel<T> {
    return new LoadingModel<T>(false, true, false, optionalSuccess, error)
  }

  loading = (success: T = this.success) => new LoadingModel(true, false, this.hasSuccess, success)

  public get success(): T {
    return this._success as T
  }

  public get optionalSuccess(): T | undefined {
    return this._success
  }

  constructor(
    public isLoading: boolean,
    private hasError: boolean,
    private hasSuccess: boolean,
    private _success?: T,
    public error?: Error) {
  }

  isEmpty = () => !this.isSuccess() && !this.isError()
  isSuccess = () => this.hasSuccess
  isError = () => this.hasError

  public toString = () => `Loading: ${this.isLoading}, Success: ${this.hasSuccess}:**${this._success}**, Error: ${this.hasError}:${this.error}`
}
```

I need to add:
```
else if (a && b && typeof a === 'function' && typeof b === 'function') {
    return a.toString() === b.toString()
  }
```
at the end of the equality check to see if both function bodies are the same, it is the same function. It seems as though _different_ class instances with same function declared in class are incorrectly getting flagged for not equal, yet they are the same and the properties are all of the same.

**Comment by epoberezkin** [comment]
Library compares functions by strict equality check. Comparing as you suggest would consider two functions equal even if they have different properties attached to them.

These are two different functions separately created as part of the instance constructor. To make them equal you need to convert them to methods.

**Comment by epoberezkin** [comment]
See https://github.com/epoberezkin/fast-deep-equal/commit/ba63e03fd12f1fc5532eed629859c18436b29b0a and #11
