### ISSUE TITLE
Attempt to use ES6 version will break in some browsers

### ISSUE THREAD

**Issue by xobotyi** [epoberezkin/fast-deep-equal#35]
Accorting to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt64Array), attempt to check `BigInt64Array` and `BigUint64Array` will throw in Safari, Samsung Internet, Edge and IE

**Comment by epoberezkin** [comment]
So what’s the suggested solution?

**Comment by xobotyi** [comment]
@epoberezkin the solution is a part of PR.
https://github.com/epoberezkin/fast-deep-equal/pull/36/files/7425c32762dc589b5efe809c2a9cd0bbcdc6d196#r301267262
