### ISSUE TITLE
Maximum call stack size exceeded for cyclic objects

### ISSUE THREAD

**Issue by smikhalevski** [epoberezkin/fast-deep-equal#37]
The code below throws the `RangeError`:
```tsx
var fastDeepEqual = require("fast-deep-equal")

const a = {aaa: 123};
a.a = a;

const b = {aaa: 123};
b.a = b;

fastDeepEqual(a,b)
```
Was loop detection omitted intentionally? If so it would be great to have paragraph on this in the docs.

**Comment by epoberezkin** [comment]
Cyclic objects are supported in beta version
