### ISSUE TITLE
False positive when a array item is modified using a non-numeric index/key

### ISSUE THREAD

**Issue by parodot** [epoberezkin/fast-deep-equal#4]
**node**: 8.9.0
**npm**: 5.5.1

The scenario below produces a false positive.
```
const fe = require('fast-deep-equal');
let oa = { 'a': 1, 'b': [1, { 'c': 'd' }], e: { 'a': [1, 2, '2'] } };
let ob = { 'a': 1, 'b': [1, { 'c': 'd' }], e: { 'a': [1, 2, '2'] } };

console.log(fe(oa,ob) ? 'equal' : 'not equal'); // equal
ob.b.c=1 // this is valid js although b is an array
console.log(fe(oa,ob) ? 'equal' :  'not equal') // equal <- incorrect
```

[Testing deep equality](https://gist.github.com/parodot/6bd1beb76c855e0244feab7ba1b4fa66) gist has more tests

**Comment by marbemac** [comment]
Are you sure that is valid?

<img width="667" alt="screen shot 2017-12-20 at 10 10 12 pm" src="https://user-images.githubusercontent.com/847542/34240308-94fa048e-e5d2-11e7-87e2-d058bf25aa1e.png">

**Comment by DavidSexton** [comment]
> ob.b.c=1 // this is valid js although b is an array

This creates a property on the array 'ob.b' named c with a value of 1.  Thus there is a difference between the object's named oa and ob, however the library states that they are equal.

**Comment by epoberezkin** [comment]
The only two packages from the benchmark that treat such arrays as not equal are deep-equal and node.js deepStrictEqual. The first one has lots of other issues (e.g 1 == true, etc.), the second is very slow.

All other packages, including lodash and underscore, treat arrays with extra properties as equal. Arguably, such behaviour is better for users given 1) the use case where this function is used and 2) assigning the properties to array is considered a bad practice anyway, so it may be better to not take it into the account in such packages.

So given that this behaviour can only be added as a non-default option and there is no way to do it without performance cost, I am going to close it. Once lodash changes it I can reconsider.

**Comment by epoberezkin** [comment]
May worth a note in docs, but if anybody makes a PR it should include the above comments about other packages.
