### ISSUE TITLE
/es6 and /es6cycles does not work with typescript

### ISSUE THREAD

**Issue by siddhant1** [epoberezkin/fast-deep-equal#40]
Typescript does compile time module resolution , so /es6 and /es6cycles import statements give error until we change the compiler options to use classic module resolution

**Comment by mokeev1995** [comment]
#48 should help (for ES6 version), when it'll be merged and published

**Comment by LinusU** [comment]
Would you mind elaborating a bit more on the problem here? All of these imports works for me:

```typescript
import equal = require('fast-deep-equal')
import equal = require('fast-deep-equal/es6')
import equal = require('fast-deep-equal/es6/react')
import equal = require('fast-deep-equal/react')
```

e.g. the `es6/index.d.ts` file lies right next to `es6/index.js`, so I don't understand how it would not be resolved 🤔
