### ISSUE TITLE
Error/testing notification

### ISSUE THREAD

**Issue by dgwyer** [epoberezkin/fast-deep-equal#41]
Just started using this fantastic utility.

After some initial tests it occurred to me that, where objects differ, it would be really useful to see precisely where they differ rather than having to manually scan the objects. This is obviously more relevant for large and deeper nested objects.

If this isn't currently possible it would be a great feature for testing when you get unexpected results. e.g. when you expect two objects to be equal but they aren't.

If performance is an issue then perhaps a setting can be enabled to switch this feature on for testing? Just an idea.

**Comment by epoberezkin** [comment]
Thank you. There are json-patch and json-merge-patch spec utilities that diff objects. Here it would be out of scope.
