### ISSUE TITLE
`fast-deep-equal/react` not found

### ISSUE THREAD

**Issue by silverwind** [epoberezkin/fast-deep-equal#46]
I get a `MODULE_NOT_FOUND` error when importing it as per README. I see no `react` folder in `node_modules`. Maybe it was not published?

**Comment by epoberezkin** [comment]
indeed!

**Comment by etiennejcharles** [comment]
Is there a reason why it's mentionned as something that can be used in react ? I'm a little confused - Thank for the package buddy 😉 !

https://www.npmjs.com/package/fast-deep-equal
![image](https://user-images.githubusercontent.com/2872476/202047418-56c29565-6fc4-4feb-a692-975e17c117da.png)

**Comment by epoberezkin** [comment]
Sorry, don’t understand the question.... What is mentioned?

**Comment by etiennejcharles** [comment]
Sorry there for the typo!

I presume it can be used in "react land", but I'm getting the same error, is there anything that else that needs to be done in order to get it working I did 


```npm install fast-deep-equal``` 

And expected 
```var equal = require('fast-deep-equal/react');```

To exist
There might be something I'm missing 

Let me know!
