### ISSUE TITLE
Set with different values but same length

### ISSUE THREAD

**Issue by cagataycali** [epoberezkin/fast-deep-equal#50]
Hi!

I've just tried your awesome work but I think something gone wrong;

```javascript
const equal = require('fast-deep-equal');
// Returns true, expected false?
console.log(equal(new Set([1, 2, 3]), new Set([1, 2, 4]))); 
```

**Comment by cagataycali** [comment]
I've fixed in locally via,

```javascript
// 37.line for es6 approach
// ....
return Array.from(a) === Array.from(b);
```

```javascript
// 53. line
if (a.__proto__ === Set.prototype && b.__proto__ === Set.prototype) return Array.from(a) === Array.from(b);
```

**Comment by epoberezkin** [comment]
It looks like you are not using es6 version - see readme how to require it.

**Comment by ryan-roemer** [comment]
@cagataycali s fix was using the es6 code and we’ve separately confirmed the bug and posted an analogous solution in our issue that tracks this one upstream. Love to see one of the two fixes land!

**Comment by epoberezkin** [comment]
Possibly it's time to release the major version that would offer es6 by default and put the current code in "/es5" folder...
