### ISSUE TITLE
for ... of loop break in IE11 with polyfills

### ISSUE THREAD

**Issue by markov00** [epoberezkin/fast-deep-equal#52]
Hi, I'm using the es6 version because I needs the Map and Set capabilities on the deep equal. 
I'm locally transpiling my code to es6 with Map and Set polyfilled via corejs, but the problem is that if I use the `/es6` version I automatically use the for...of loops that can't be used in IE11.
Is there any chance to avoid the for of loops?

**Comment by epoberezkin** [comment]
@markov00 you need to build and transpire code for the target platform.
