### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by softaria-roman** [epoberezkin/fast-deep-equal#66]
Maybe I have misunderstood something , but why this line should work in general case?

if (a.toString !== Object.prototype.toString) return a.toString() === b.toString();

What if I have my own toString and it, for example, always returns the same constant, no matter what the object is?

At least the following typescript code prints "true"

```
class A {
    n:number;
    constructor(n:number) {
        this.n = n;
    }
    toString():string  {
        return "a";
    }

}

const a1 = new A(1);
const a2 = new A(2);

if (a1.toString !== Object.prototype.toString) {
    const ret = a1.toString() === a2.toString();
    console.log(ret);
}
```

**Comment by epoberezkin** [comment]
Custom toString method is supposed to be used to generate string representation of the object - the idea here is that if it was overridden in some useful way as Mozilla recommends (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toString) then it would generate equal representation for equal objects, and unequal for unequal. Of course it can be defined in not as useful way, as in your example (in the same way as custom equality operator in some other languages can be defined to do what you want)...

**Comment by softaria-roman** [comment]
Thank you for the answer. However, I think it probably should be added to the documentation to prevent possible confusion. Of course, nobody would return constant in toString(), but I saw toString() implementations that ignore part of of object attributes (probably for historical reason). It may lead to rather bad bugs.
