### ISSUE TITLE
Publish 3.1.2

### ISSUE THREAD

**Issue by streamich** [epoberezkin/fast-deep-equal#69]
Could you please publish to NPM the latest typing fixes? https://github.com/epoberezkin/fast-deep-equal/commit/c91f5e7d19ba4064d145824e702ccec0a2a3bcab

**Comment by epoberezkin** [comment]
Tomorrow morning

**Comment by epoberezkin** [comment]
published 3.1.3

**Comment by macrozone** [comment]
@epoberezkin it is actually not fixed in 3.1.3. it still contains the wrong type definition. please reopen
