### ISSUE TITLE
source code question

### ISSUE THREAD

**Issue by iamwelk** [epoberezkin/fast-deep-equal#74]
1. What's the meaning of following source code?
```javascript
{{? it.es6 }}
...
{{?}}
```
2. Why not use Object.is to check NaN
```javascript
// return a!==a && b!==b;
return Object.is(a, b)
```

**Comment by shashank1010** [comment]
Never used it but maybe this file will help you understand.
[https://github.com/epoberezkin/fast-deep-equal/blob/master/build.js](url)

the code is conditionally added at build time thus making the bundles smaller

**Comment by epoberezkin** [comment]
correct, the code is doT template that is used to generate different variants of the same utility.
