### ISSUE TITLE
Throws error when comparing circular objects

### ISSUE THREAD

**Issue by zhangbenber** [epoberezkin/fast-deep-equal#8]
Test code:
```
const equal = require('fast-deep-equal');

let a = {};
a.test = a;
let b = {};
b.test = b;

console.log(equal(a, b));
// Throws RangeError: Maximum call stack size exceeded
```

Any ideas for loop detecting before compare?

**Comment by epoberezkin** [comment]
You could just wrap in try/catch and check the error. Loop detection has performance cost, so unless you expect them it is not justified.
