### ISSUE TITLE
Not able to compare a Map

### ISSUE THREAD

**Issue by AaronRobinson** [epoberezkin/fast-deep-equal#82]
console.log(equal(Int16Array([1, 2]), Int16Array([1, 3]))) fails with "TypeError: Constructor Int16Array requires 'new'"
console.log(equal(new Int16Array([1, 2]), new Int16Array([1, 3]))) outputs true

Am I doing something silly?

**Comment by epoberezkin** [comment]
Possibly, you need to import ES6 version?

**Comment by AaronRobinson** [comment]
```
const assert = require('assert')
var equal = require('fast-deep-equal/es6')
const a = new Map([
  [1, 'one'],
  [2, 'two'],
  [3, 'three']
])
const b = new Map([
  [1, 'one'],
  [2, 'two'],
  [4, 'three']
])
console.log(equal(new Int16Array(a), new Int16Array(b)))
```

This outputs true. Is this expected?

**Comment by epoberezkin** [comment]
I don’t think you are using Int16Array correctly - its constructor has no arguments, so both arrays are empty and therefore equal.

**Comment by epoberezkin** [comment]
Actually it’s argument is length or array - didn’t read spec to the end. No idea what happens when you pass the map

**Comment by epoberezkin** [comment]
Maybe because all items of the iterable are not integers they become zeroes?

**Comment by epoberezkin** [comment]
See this test: https://github.com/epoberezkin/fast-deep-equal/blob/master/spec/es6tests.js#L298
